### ISSUE TITLE
Web service URLs should be in config for the build

### ISSUE THREAD

**Issue by danblundell** [lgss/rekommend-manage#9]
The URLs for web services should be in configuration management as variables in the build

**Comment by 13enedict** [comment]
We're already working on abstracting the endpoints and other basic configuration information out into a separate configuration file that can be packaged as part of the release. We made a conscious design choice not to do bake these variables in with the build because:

1. the system has two websites, and each uses a slightly different build process. One uses webpack, and the other uses vue-client-service. This means that we'd have to do two different processes for compiling in the endpoints, and;
2. by using a configuration JSON file it means that we could move builds between dev, staging, and live without having to recompile and risk the package being altered by external factors.

**Comment by danblundell** [comment]
PR #11 resolves this
